### ISSUE TITLE
QuerySetJob always fails with - <model> is not JSON serializable

### ISSUE THREAD

**Issue by macolo** [codeinthehole/django-cacheback#79] opened 2018-06-27 15:23 UTC
When we use `QuerySetJob` we get an error when django-cacheback enqueues a caching job with celery: <model> is not JSON serializable

 I wonder how this was intended to work?

The QuerySetJob enqueues the model class. How can `kombu` serialize a model class?

https://github.com/codeinthehole/django-cacheback/blob/ef63b4c903da822ac16d980668dacc1fc9f6ba9c/cacheback/jobs.py#L75

https://github.com/codeinthehole/django-cacheback/blob/master/cacheback/base.py#L321

![image](https://user-images.githubusercontent.com/4056979/41983451-6d92e7da-7a2e-11e8-8ba9-76b9e206cc7f.png)

**Comment by stephrdev** [comment] 2018-07-11 11:53
Hi!
This is a custom feature you implemented and not part of cacheback.

All args and kwargs you pass to a cache job need to be json-serializable. A python class cannot be serialized using JSON. You might want to use a string which is usable with apps.get_model from Django.

Hope this helps. I'm closing the issue as it's not a bug in cacheback.

Thanks!

**Closed by stephrdev** 2018-07-11 11:53 UTC
